export const ADMIN_ROUTE='/admin'
export const LOGIN_ROUTE='/login'
export const REGISTATION_ROUTE='/registration'
export const MAIN_ROUTE='/'
export const APPOINTMENT_ROUTE='/appointment'
export const STATISTICS_ROUTE='/statistics'